# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest 
    variables:
       tags: $(Build.BuildId)   

    steps:

    - script: |
        python3 --version
        pip3 --version
        pip3 install pyinstaller
      
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQube-DEV'
        scannerMode: 'MSBuild'
        projectKey: 'catlogmgmt'
        projectName: 'Catalog Mgmt Service'
        extraProperties: |
          sonar.exclusions=**/obj/**,**/*.dll
          sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
          sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage"'
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Agent.TempDirectory)\*.coverage'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
    - task: SonarQubeAnalyze@5
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

    - task: CopyFiles@2
      displayName: Copy Dev Artifacts
      inputs:
        Contents: 'Deploy/deployment.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish Dev Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: Docker@2
      displayName: Build a Dev image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Meridian.CatalogManagement/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        repository: '$(AWS_ECR_REPOSITORY_URI)'
        tags: |
          $(Build.BuildId)     
          
    - task: ECRPushImage@1
      displayName: Push an Image to Dev ECR
      inputs:
        awsCredentials: '$(AWS_CREDENTIALS)'
        regionName: '$(AWS_REGION)'
        imageSource: 'imagename'
        sourceImageName: '$(AWS_ECR_REPOSITORY_URI)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: '$(AWS_ECR_REPOSITORY_NAME)'
        pushTag: '$(Build.BuildId)'
        
    - task: CopyFiles@2
      displayName: Copy Files to QA
      inputs:
        Contents: 'QaDeploy/deployment.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: Publish QA Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container' 
        
    - task: Docker@2
      displayName: Build a QA image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Meridian.CatalogManagement/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        repository: '$(AWS_QA_ECR_REPOSITORY_URI)'
        tags: |
          $(Build.BuildId)   
    - task: ECRPushImage@1
      displayName: push an Image to QA-ECR
      inputs:
        awsCredentials: '$(AWS_QA_CREDENTIALS)'
        regionName: '$(AWS_QA_REGION)'
        imageSource: 'imagename'
        sourceImageName: '$(AWS_QA_ECR_REPOSITORY_URI)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: '$(AWS_QA_ECR_REPOSITORY_NAME)'
        pushTag: '$(Build.BuildId)'
    
    - task: CopyFiles@2
      displayName: Copy Files to UAT
      inputs:
        Contents: 'Deploy-Uat/deployment.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
        
    - task: PublishBuildArtifacts@1
      displayName: Publish UAT Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container' 
        

    - task: Docker@2
      displayName: Build a UAT image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Meridian.CatalogManagement/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        repository: '$(AWS_UAT_ECR_REPOSITORY_URI)'
        tags: |
          $(Build.BuildId)
             
    - task: ECRPushImage@1
      displayName: push an Image to UAT-ECR
      inputs:
        awsCredentials: '$(AWS_UAT_CREDENTIALS)'
        regionName: '$(AWS_UAT_REGION)'
        imageSource: 'imagename'
        sourceImageName: '$(AWS_UAT_ECR_REPOSITORY_URI)'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: '$(AWS_UAT_ECR_REPOSITORY_NAME)'
        pushTag: '$(Build.BuildId)'
    
    # - task: SonarQubeAnalyze@5
    # - task: SonarQubePublish@5
    #   inputs:
    #     pollingTimeoutSec: '300'