apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qa-user-mgmt-svc
  name: qa-user-mgmt-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-user-mgmt-svc
  template:
    metadata:
      labels:
        app: qa-user-mgmt-svc
    spec:
      containers:
      - name: qa-user-mgmt-svc
        image: #{qaAccountId}#.dkr.ecr.us-west-2.amazonaws.com/qa-user-mgmt-svc:#{Build.BuildId}#
        imagePullPolicy: Always
         
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qa-user-mgmt-svc
    k8s-app: qa-user-mgmt-svc
  name: qa-user-mgmt-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: LoadBalancer
  selector:
    app: qa-user-mgmt-svc